import type { Category, Product } from './types';
import React from 'react';
import { CleaningIcon, StationeryIcon, PackagingIcon, FoodIcon } from './components/icons/CategoryIcons';

export const CATEGORIES: Category[] = [
  { name: 'Janitorial', icon: <CleaningIcon />, path: 'janitorial' },
  { name: 'Stationery', icon: <StationeryIcon />, path: 'stationery' },
  { name: 'Packaging', icon: <PackagingIcon />, path: 'packaging' },
  { name: 'Food & Beverage', icon: <FoodIcon />, path: 'food-and-beverage' },
];

export const JANITORIAL_PRODUCTS: Product[] = [
  { id: 1, name: 'Wiping Cloth White [1 Pc]', price: 50, description: 'Absorbent white wiping cloth for general cleaning. Price includes GST.', imageUrl: 'https://picsum.photos/seed/wipingcloth/400/400', category: 'Janitorial' },
  { id: 2, name: 'Floor Brush 18 [1 No]', price: 21, description: 'Durable 18-inch floor brush for scrubbing tough dirt. Price includes GST.', imageUrl: 'https://picsum.photos/seed/floorbrush/400/400', category: 'Janitorial' },
  { id: 3, name: 'Floor Cl Duster [1 Pc]', price: 24, description: 'Cotton floor duster for effective dust removal. Price includes GST.', imageUrl: 'https://picsum.photos/seed/floorduster/400/400', category: 'Janitorial' },
  { id: 4, name: 'Green Scrubling Pad [1 Pc]', price: 531, description: 'Heavy-duty green scrubbing pad for tough stains. Price includes GST.', imageUrl: 'https://picsum.photos/seed/greenscrub/400/400', category: 'Janitorial' },
  { id: 5, name: 'Green Scotch Pad', price: 14, description: 'Versatile green scotch pad for kitchen and surface cleaning. Price includes GST.', imageUrl: 'https://picsum.photos/seed/scotchpad/400/400', category: 'Janitorial' },
  { id: 6, name: 'Nylon Scrubber', price: 11, description: 'Durable nylon scrubber for non-stick cookware and delicate surfaces. Price includes GST.', imageUrl: 'https://picsum.photos/seed/nylonscrubber/400/400', category: 'Janitorial' },
  { id: 7, name: 'Magic Scruber Pad', price: 21, description: 'Magic eraser pad for removing tough marks with just water. Price includes GST.', imageUrl: 'https://picsum.photos/seed/magicscrubber/400/400', category: 'Janitorial' },
  { id: 8, name: 'Steel Scrubber Mazic', price: 14, description: 'Stainless steel scrubber for removing stubborn, burnt-on food. Price includes GST.', imageUrl: 'https://picsum.photos/seed/steelscrubber/400/400', category: 'Janitorial' },
  { id: 9, name: 'Plastic Wiper 18[1]', price: 141, description: '18-inch plastic floor wiper for quick drying of floors. Price includes GST.', imageUrl: 'https://picsum.photos/seed/plasticwiper/400/400', category: 'Janitorial' },
  { id: 10, name: 'Wet Mop Refile [1 No]', price: 141, description: 'High-quality cotton refill for wet mops. Price includes GST.', imageUrl: 'https://picsum.photos/seed/moprefill/400/400', category: 'Janitorial' },
  { id: 11, name: 'Wet Mop Set Round [1 No]', price: 88, description: 'Complete round wet mop set with handle. Price includes GST.', imageUrl: 'https://picsum.photos/seed/mopset/400/400', category: 'Janitorial' },
  { id: 12, name: 'Toilet Brush Round', price: 171, description: 'Round toilet brush with holder for effective cleaning. Price includes GST.', imageUrl: 'https://picsum.photos/seed/toiletbrush/400/400', category: 'Janitorial' },
  { id: 13, name: 'Wonder Wipe [1 Pk]', price: 56, description: 'Cellulose-based sponge wipe for kitchen and table cleaning. Price includes GST.', imageUrl: 'https://picsum.photos/seed/wonderwipe/400/400', category: 'Janitorial' },
  { id: 14, name: 'Mop Wiper Stick 5 FT', price: 123, description: '5-foot long, sturdy stick for mops and wipers. Price includes GST.', imageUrl: 'https://picsum.photos/seed/mopstick/400/400', category: 'Janitorial' },
  { id: 15, name: 'Hard Broom [1 No]', price: 59, description: 'Hard bristle broom for outdoor and rough surface sweeping. Price includes GST.', imageUrl: 'https://picsum.photos/seed/hardbroom/400/400', category: 'Janitorial' },
  { id: 16, name: 'Duster Checks[1]', price: 53, description: 'Checkered cloth duster for all-purpose cleaning. Price includes GST.', imageUrl: 'https://picsum.photos/seed/checkduster/400/400', category: 'Janitorial' },
  { id: 17, name: 'Dry mop set 18" Blue', price: 13, description: '18-inch blue dry mop set, ideal for dust and hair. Price includes GST.', imageUrl: 'https://picsum.photos/seed/drymopset/400/400', category: 'Janitorial' },
  { id: 18, name: 'Dry mop Reffil 18" Blue', price: 413, description: '18-inch blue refill for dry mops. Price includes GST.', imageUrl: 'https://picsum.photos/seed/drymoprefill/400/400', category: 'Janitorial' },
  { id: 19, name: 'Dry mop bracket 18x4"', price: 151, description: 'Sturdy 18x4 inch bracket for dry mops. Price includes GST.', imageUrl: 'https://picsum.photos/seed/drymopbracket/400/400', category: 'Janitorial' },
  { id: 20, name: 'Soft Broom', price: 159, description: 'Soft bristle broom for indoor and smooth surface sweeping. Price includes GST.', imageUrl: 'https://picsum.photos/seed/softbroom/400/400', category: 'Janitorial' },
  { id: 21, name: 'Squzee Bottle [1Pc]', price: 165, description: '500ml squeeze bottle for dispensing cleaning liquids. Price includes GST.', imageUrl: 'https://picsum.photos/seed/squeezebottle/400/400', category: 'Janitorial' },
  { id: 22, name: 'Bottle Cleaning Brush', price: 33, description: 'Long-handle brush for cleaning bottles and narrow containers. Price includes GST.', imageUrl: 'https://picsum.photos/seed/bottlebrush/400/400', category: 'Janitorial' },
  { id: 23, name: 'Ross Fcs Dishwash Concetrate [1 Lt]', price: 850, description: 'Concentrated dishwash liquid, 1 liter. Price includes GST.', imageUrl: 'https://picsum.photos/seed/dishwash/400/400', category: 'Janitorial' },
  { id: 24, name: 'Phynoil Ltr', price: 200, description: '1 liter of Phenyl concentrate for disinfecting floors. Price includes GST.', imageUrl: 'https://picsum.photos/seed/phenyl/400/400', category: 'Janitorial' },
  { id: 25, name: 'Bleaching Powder', price: 41, description: 'Effective bleaching powder for sanitation and whitening. Price includes GST.', imageUrl: 'https://picsum.photos/seed/bleach/400/400', category: 'Janitorial' },
  { id: 26, name: 'Dishwash Liquid [1 Lt)', price: 318, description: 'Ready-to-use dishwash liquid, 1 liter. Price includes GST.', imageUrl: 'https://picsum.photos/seed/dishwashliquid/400/400', category: 'Janitorial' },
  { id: 27, name: 'Washing Pdr [1 Kg]', price: 70, description: '1 kg of multi-purpose washing powder for laundry. Price includes GST.', imageUrl: 'https://picsum.photos/seed/washingpowder/400/400', category: 'Janitorial' },
  { id: 28, name: 'Caustic Soda [1 Kg]', price: 165, description: '1 kg of caustic soda for heavy-duty cleaning and drain opening. Price includes GST.', imageUrl: 'https://picsum.photos/seed/causticsoda/400/400', category: 'Janitorial' },
  { id: 29, name: 'Air Freshner Can [1 No)', price: 650, description: 'Automatic air freshener can for long-lasting fragrance. Price includes GST.', imageUrl: 'https://picsum.photos/seed/airfreshener/400/400', category: 'Janitorial' },
  { id: 30, name: 'Essential Oil - Lemon Grass [1 Lt]', price: 1800, description: '1 liter of pure lemon grass essential oil for aromatherapy and cleaning. Price includes GST.', imageUrl: 'https://picsum.photos/seed/lemongrassoil/400/400', category: 'Janitorial' },
  { id: 31, name: 'Drainex Drain Cleaner Pdr', price: 17, description: 'Powder drain cleaner to clear clogged pipes. Price includes GST.', imageUrl: 'https://picsum.photos/seed/drainex/400/400', category: 'Janitorial' },
  { id: 32, name: 'Garbage Bags 19X21 [1 Pk]', price: 59, description: 'Pack of medium-sized garbage bags (19x21 inches). Price includes GST.', imageUrl: 'https://picsum.photos/seed/garbagebagmedium/400/400', category: 'Janitorial' },
  { id: 33, name: 'Garbage Bag 29X39 [1 Pk]', price: 70, description: 'Pack of large-sized garbage bags (29x39 inches). Price includes GST.', imageUrl: 'https://picsum.photos/seed/garbagebaglarge/400/400', category: 'Janitorial' },
];

export const STATIONERY_PRODUCTS: Product[] = [
  { id: 101, name: 'BoxFileKangaro', price: 80.00, description: 'Durable Kangaro box file for document storage. Price includes GST.', imageUrl: 'https://picsum.photos/seed/BoxFileKangaro/400/400', category: 'Stationery' },
  { id: 102, name: 'VoucherBoxFileSteelClip', price: 65.00, description: 'Box file with a strong steel clip for vouchers. Price includes GST.', imageUrl: 'https://picsum.photos/seed/VoucherBoxFileSteelClip/400/400', category: 'Stationery' },
  { id: 103, name: 'BoxFileSteel Laminate', price: 70.00, description: 'Laminated steel box file for extra durability. Price includes GST.', imageUrl: 'https://picsum.photos/seed/BoxFileSteelLaminate/400/400', category: 'Stationery' },
  { id: 104, name: 'BoxFileSteelClip', price: 65.00, description: 'Standard box file with a reliable steel clip. Price includes GST.', imageUrl: 'https://picsum.photos/seed/BoxFileSteelClip/400/400', category: 'Stationery' },
  { id: 105, name: 'BoxFileKangaro Laminate-2DRing', price: 65.00, description: 'Laminated 2-D ring binder from Kangaro. Price includes GST.', imageUrl: 'https://picsum.photos/seed/BoxFileKangaroLaminate-2DRing/400/400', category: 'Stationery' },
  { id: 106, name: 'PVCSpringFile302F/c', price: 50.00, description: 'Foolscap size PVC spring file, model 302. Price includes GST.', imageUrl: 'https://picsum.photos/seed/PVCSpringFile302Fc/400/400', category: 'Stationery' },
  { id: 107, name: 'PVCSpringFile301A/4', price: 45.00, description: 'A4 size PVC spring file, model 301. Price includes GST.', imageUrl: 'https://picsum.photos/seed/PVCSpringFile301A4/400/400', category: 'Stationery' },
  { id: 108, name: 'R-CFileA/4', price: 15.00, description: 'A4 size record-cobra file. Price includes GST.', imageUrl: 'https://picsum.photos/seed/RCFileA4/400/400', category: 'Stationery' },
  { id: 109, name: 'LaminaMoraccoFileF/c', price: 15.00, description: 'Foolscap size laminated Morocco file. Price includes GST.', imageUrl: 'https://picsum.photos/seed/LaminaMoraccoFileFc/400/400', category: 'Stationery' },
  { id: 110, name: 'Lamina MoraccoFileA/4', price: 14.00, description: 'A4 size laminated Morocco file. Price includes GST.', imageUrl: 'https://picsum.photos/seed/LaminaMoraccoFileA4/400/400', category: 'Stationery' },
  { id: 111, name: 'PattiFileA/4', price: 13.00, description: 'A4 size Patti file for simple document holding. Price includes GST.', imageUrl: 'https://picsum.photos/seed/PattiFileA4/400/400', category: 'Stationery' },
  { id: 112, name: 'PattiFileChinaA/4', price: 15.00, description: 'A4 size China Patti file. Price includes GST.', imageUrl: 'https://picsum.photos/seed/PattiFileChinaA4/400/400', category: 'Stationery' },
  { id: 113, name: 'A/4JKEasy Paper70 Gsm JK', price: 245.00, description: 'A4 size 70 GSM paper ream from JK. Price includes GST.', imageUrl: 'https://picsum.photos/seed/A4JKEasyPaper70GsmJK/400/400', category: 'Stationery' },
  { id: 114, name: 'A/4JK Red Paper 75 Gsm JK', price: 265.00, description: 'A4 size 75 GSM paper ream from JK Red. Price includes GST.', imageUrl: 'https://picsum.photos/seed/A4JKRedPaper75GsmJK/400/400', category: 'Stationery' },
  { id: 115, name: 'A/4 B2BPaper 70Gsm B2B', price: 245.00, description: 'A4 size 70 GSM paper ream from B2B. Price includes GST.', imageUrl: 'https://picsum.photos/seed/A4B2BPaper70GsmB2B/400/400', category: 'Stationery' },
  { id: 116, name: 'PaperCutterBig', price: 15.00, description: 'Large paper cutter for office use. Price includes GST.', imageUrl: 'https://picsum.photos/seed/PaperCutterBig1/400/400', category: 'Stationery' },
  { id: 117, name: 'PaperCutterSmall', price: 8.00, description: 'Small, handy paper cutter. Price includes GST.', imageUrl: 'https://picsum.photos/seed/PaperCutterSmall/400/400', category: 'Stationery' },
  { id: 118, name: 'PaperCutter-Big', price: 65.00, description: 'Heavy-duty large paper cutter. Price includes GST.', imageUrl: 'https://picsum.photos/seed/PaperCutterBig2/400/400', category: 'Stationery' },
  { id: 119, name: 'Tachni Pin250Gms', price: 80.00, description: '250 Gms box of technical pins. Price includes GST.', imageUrl: 'https://picsum.photos/seed/TachniPin250Gms/400/400', category: 'Stationery' },
  { id: 120, name: 'TachniPin50Gm', price: 25.00, description: '50 Gms box of technical pins. Price includes GST.', imageUrl: 'https://picsum.photos/seed/TachniPin50Gm/400/400', category: 'Stationery' },
  { id: 121, name: 'Natraj Pencils', price: 43.00, description: 'A pack of classic Natraj pencils. Price includes GST.', imageUrl: 'https://picsum.photos/seed/NatrajPencils/400/400', category: 'Stationery' },
  { id: 122, name: 'Apsara Pencils', price: 52.00, description: 'A pack of high-quality Apsara pencils. Price includes GST.', imageUrl: 'https://picsum.photos/seed/ApsaraPencils/400/400', category: 'Stationery' },
  { id: 123, name: 'ApsaraGlass Pencil', price: 60.00, description: 'Apsara pencil for writing on glass surfaces. Price includes GST.', imageUrl: 'https://picsum.photos/seed/ApsaraGlassPencil/400/400', category: 'Stationery' },
  { id: 124, name: '12"PlasticScale', price: 12.00, description: '12-inch durable plastic scale. Price includes GST.', imageUrl: 'https://picsum.photos/seed/12PlasticScale/400/400', category: 'Stationery' },
  { id: 125, name: '12"SteelScal', price: 35.00, description: '12-inch sturdy steel scale. Price includes GST.', imageUrl: 'https://picsum.photos/seed/12SteelScal/400/400', category: 'Stationery' },
  { id: 126, name: '6"SteelScale', price: 15.00, description: '6-inch handy steel scale. Price includes GST.', imageUrl: 'https://picsum.photos/seed/6SteelScale/400/400', category: 'Stationery' },
  { id: 127, name: 'Permanent Marker', price: 16.50, description: 'Permanent marker for various surfaces. Price includes GST.', imageUrl: 'https://picsum.photos/seed/PermanentMarker/400/400', category: 'Stationery' },
  { id: 128, name: 'WhiteBoardMarker', price: 22.00, description: 'Whiteboard marker with easy wipe ink. Price includes GST.', imageUrl: 'https://picsum.photos/seed/WhiteBoardMarker/400/400', category: 'Stationery' },
  { id: 129, name: 'WhitePaintMarker', price: 40.00, description: 'White paint marker for opaque marking. Price includes GST.', imageUrl: 'https://picsum.photos/seed/WhitePaintMarker/400/400', category: 'Stationery' },
  { id: 130, name: 'Highlighter', price: 30.00, description: 'Bright highlighter for text marking. Price includes GST.', imageUrl: 'https://picsum.photos/seed/Highlighter/400/400', category: 'Stationery' },
  { id: 131, name: 'HighlighterInk', price: 18.00, description: 'Refill ink for highlighters. Price includes GST.', imageUrl: 'https://picsum.photos/seed/HighlighterInk/400/400', category: 'Stationery' },
  { id: 132, name: 'CorrectionPen', price: 24.00, description: 'Correction pen for easy error fixing. Price includes GST.', imageUrl: 'https://picsum.photos/seed/CorrectionPen/400/400', category: 'Stationery' },
];

export const PACKAGING_PRODUCTS: Product[] = [
  { id: 201, name: 'Parcel Container 100 ml black', price: 4.13, description: '100ml black parcel container for small portions. Price includes GST.', imageUrl: 'https://picsum.photos/seed/parcel100ml/400/400', category: 'Packaging' },
  { id: 202, name: 'Parcel Cont. 750 ml rect. Black', price: 10.62, description: '750ml rectangular black container for meals. Price includes GST.', imageUrl: 'https://picsum.photos/seed/parcel750ml/400/400', category: 'Packaging' },
  { id: 203, name: 'Parcel Contener 250 blake', price: 5.31, description: '250ml black container, ideal for side dishes. Price includes GST.', imageUrl: 'https://picsum.photos/seed/parcel250ml/400/400', category: 'Packaging' },
  { id: 204, name: 'Parcel Contianer Round black 500ml', price: 7.67, description: '500ml round black container for gravies and curries. Price includes GST.', imageUrl: 'https://picsum.photos/seed/parcel500ml/400/400', category: 'Packaging' },
  { id: 205, name: 'Parcel container 650ml rect. Black', price: 10.62, description: '650ml rectangular black container for larger meals. Price includes GST.', imageUrl: 'https://picsum.photos/seed/parcel650ml/400/400', category: 'Packaging' },
  { id: 206, name: 'Lunch Parcel Tray 8 Cp Black w/Id', price: 18.00, description: '8-compartment black lunch tray with lid. Price includes GST.', imageUrl: 'https://picsum.photos/seed/tray8cp/400/400', category: 'Packaging' },
  { id: 207, name: 'Lunch Parcel Tray 3 Cp [1 Pc]', price: 14.16, description: '3-compartment lunch tray for combo meals. Price includes GST.', imageUrl: 'https://picsum.photos/seed/tray3cp/400/400', category: 'Packaging' },
  { id: 208, name: 'DIP SALICE VATI SMALL ACRALIC', price: 2.95, description: 'Small acrylic bowl for dips and sauces. Price includes GST.', imageUrl: 'https://picsum.photos/seed/dipvati/400/400', category: 'Packaging' },
  { id: 209, name: 'Disposible Vati [1 Pc]', price: 2.95, description: 'Standard disposable bowl for single servings. Price includes GST.', imageUrl: 'https://picsum.photos/seed/disposablevati/400/400', category: 'Packaging' },
  { id: 210, name: 'Muffins Paper Cup 500/pkt', price: 177.00, description: 'Pack of 500 paper cups for muffins and cupcakes. Price includes GST.', imageUrl: 'https://picsum.photos/seed/muffincup/400/400', category: 'Packaging' },
  { id: 211, name: 'PAPER CUP 100 ML PLAIN', price: 0.94, description: '100ml plain paper cup for beverages. Price includes GST.', imageUrl: 'https://picsum.photos/seed/papercup100/400/400', category: 'Packaging' },
  { id: 212, name: 'Paper Parcel Carry Bag 9x11[1 pc]', price: 7.67, description: '9x11 inch paper bag for takeaways. Price includes GST.', imageUrl: 'https://picsum.photos/seed/paperbag9x11/400/400', category: 'Packaging' },
  { id: 213, name: 'Paper Straw [1 Pk]', price: 61.60, description: 'Eco-friendly pack of paper straws. Price includes GST.', imageUrl: 'https://picsum.photos/seed/paperstraw/400/400', category: 'Packaging' },
  { id: 214, name: 'Sathe Sticks 100/Pkt [1 Pk]', price: 53.10, description: 'Pack of 100 wooden satay sticks. Price includes GST.', imageUrl: 'https://picsum.photos/seed/sataysticks/400/400', category: 'Packaging' },
  { id: 215, name: 'Cling Wrap 600Mtr Roll (1 No)', price: 590.00, description: '600-meter roll of food-grade cling wrap. Price includes GST.', imageUrl: 'https://picsum.photos/seed/clingwrap/400/400', category: 'Packaging' },
  { id: 216, name: 'Parchment Paper [1 Pc]', price: 359.90, description: 'Roll of non-stick parchment paper for baking. Price includes GST.', imageUrl: 'https://picsum.photos/seed/parchment/400/400', category: 'Packaging' },
  { id: 217, name: 'Silver Foil 1Kg Roll [1 No]', price: 708.00, description: '1kg roll of high-quality aluminum foil. Price includes GST.', imageUrl: 'https://picsum.photos/seed/silverfoil/400/400', category: 'Packaging' },
  { id: 218, name: 'Butter Paper', price: 212.40, description: 'Roll of butter paper for food wrapping. Price includes GST.', imageUrl: 'https://picsum.photos/seed/butterpaper/400/400', category: 'Packaging' },
  { id: 219, name: 'Silver foiled bag 6x10', price: 84.96, description: '6x10 inch silver foil bag for keeping food warm. Price includes GST.', imageUrl: 'https://picsum.photos/seed/foilbag/400/400', category: 'Packaging' },
  { id: 220, name: 'Poly bag virgin for packing', price: 160.00, description: 'Virgin poly bags for general packing purposes. Price includes GST.', imageUrl: 'https://picsum.photos/seed/polybag/400/400', category: 'Packaging' },
  { id: 221, name: 'KIRANA BAG POLYBAG 5KG', price: 2.36, description: '5kg capacity polybag for groceries. Price includes GST.', imageUrl: 'https://picsum.photos/seed/kiranabag/400/400', category: 'Packaging' },
  { id: 222, name: 'STICKERS FOR PARCEL (SHEET)', price: 177.00, description: 'Sheet of stickers for sealing and labeling parcels. Price includes GST.', imageUrl: 'https://picsum.photos/seed/parcelstickers/400/400', category: 'Packaging' },
  { id: 223, name: 'HOTEL STICKERS FOR PARCEL SHEETS', price: 188.80, description: 'Customizable hotel stickers for branding parcels. Price includes GST.', imageUrl: 'https://picsum.photos/seed/hotelstickers/400/400', category: 'Packaging' },
  { id: 224, name: 'Toothpic Regular [1 Bx]', price: 156.80, description: 'Box of regular wooden toothpicks. Price includes GST.', imageUrl: 'https://picsum.photos/seed/toothpickbox/400/400', category: 'Packaging' },
  { id: 225, name: 'Tooth Pick (Hcp) [1 Pk]', price: 179.20, description: 'Individually wrapped toothpicks pack. Price includes GST.', imageUrl: 'https://picsum.photos/seed/toothpickpack/400/400', category: 'Packaging' },
  { id: 226, name: 'Wooden Spoon/Fork [1 Pc]', price: 0.94, description: 'Disposable wooden spoon or fork. Price includes GST.', imageUrl: 'https://picsum.photos/seed/woodenspoon/400/400', category: 'Packaging' },
];

export const FOOD_AND_BEVERAGE_PRODUCTS: Product[] = [
  { id: 301, name: 'Wheat Bran', price: 150.00, description: 'High-fiber wheat bran for baking and cooking. Price includes GST.', imageUrl: 'https://picsum.photos/seed/WheatBran/400/400', category: 'Food & Beverage' },
  { id: 302, name: 'Black Cherry Dry', price: 850.00, description: 'Dried black cherries, perfect for desserts and snacks. Price includes GST.', imageUrl: 'https://picsum.photos/seed/BlackCherryDry/400/400', category: 'Food & Beverage' },
  { id: 303, name: 'White Oats', price: 210.00, description: 'Premium white oats for a healthy breakfast. Price includes GST.', imageUrl: 'https://picsum.photos/seed/WhiteOats/400/400', category: 'Food & Beverage' },
  { id: 304, name: 'Banana Essence (500ml)', price: 250.00, description: 'Concentrated banana essence for flavoring. 500ml bottle. Price includes GST.', imageUrl: 'https://picsum.photos/seed/BananaEssence/400/400', category: 'Food & Beverage' },
  { id: 305, name: 'Blueberry Fruit Filling Mala\'s 1 kg', price: 550.00, description: 'Mala\'s 1kg blueberry fruit filling for pies and pastries. Price includes GST.', imageUrl: 'https://picsum.photos/seed/BlueberryFilling/400/400', category: 'Food & Beverage' },
  { id: 306, name: 'Sunflower seeds (500 Gms Pkt.)', price: 300.00, description: '500 Gms pack of nutritious sunflower seeds. Price includes GST.', imageUrl: 'https://picsum.photos/seed/SunflowerSeeds/400/400', category: 'Food & Beverage' },
  { id: 307, name: 'White Chocolate (Morde)', price: 420.00, description: 'Morde white chocolate compound for baking. Price includes GST.', imageUrl: 'https://picsum.photos/seed/WhiteChocolate/400/400', category: 'Food & Beverage' },
  { id: 308, name: 'Orange Juice', price: 120.00, description: 'Freshly squeezed orange juice concentrate. Price includes GST.', imageUrl: 'https://picsum.photos/seed/OrangeJuice/400/400', category: 'Food & Beverage' },
  { id: 309, name: 'Orange Crush 750 ml', price: 280.00, description: '750ml bottle of rich orange crush for beverages. Price includes GST.', imageUrl: 'https://picsum.photos/seed/OrangeCrush/400/400', category: 'Food & Beverage' },
  { id: 310, name: 'Multigrain Seeds', price: 350.00, description: 'A healthy mix of various multigrain seeds. Price includes GST.', imageUrl: 'https://picsum.photos/seed/MultigrainSeeds/400/400', category: 'Food & Beverage' },
  { id: 311, name: 'Coffee Powder (500 Gms Pkt.)', price: 450.00, description: '500 Gms pack of premium coffee powder. Price includes GST.', imageUrl: 'https://picsum.photos/seed/CoffeePowder/400/400', category: 'Food & Beverage' },
  { id: 312, name: 'Mascarpone Cheese (400 Gms. Pkt.)', price: 600.00, description: '400 Gms pack of creamy Mascarpone cheese. Price includes GST.', imageUrl: 'https://picsum.photos/seed/MascarponeCheese/400/400', category: 'Food & Beverage' },
  { id: 313, name: 'Mango Pulp (1 Kg Tin)', price: 320.00, description: '1 Kg tin of sweet mango pulp. Price includes GST.', imageUrl: 'https://picsum.photos/seed/MangoPulp/400/400', category: 'Food & Beverage' },
  { id: 314, name: 'Cream Cheese (Delecta)', price: 480.00, description: 'Delecta cream cheese for spreads and desserts. Price includes GST.', imageUrl: 'https://picsum.photos/seed/CreamCheese/400/400', category: 'Food & Beverage' },
  { id: 315, name: 'Cranberry Dry', price: 750.00, description: 'Sweet and tangy dried cranberries. Price includes GST.', imageUrl: 'https://picsum.photos/seed/CranberryDry/400/400', category: 'Food & Beverage' },
  { id: 316, name: 'Black Olive', price: 250.00, description: 'Pitted black olives in brine. Price includes GST.', imageUrl: 'https://picsum.photos/seed/BlackOlive/400/400', category: 'Food & Beverage' },
  { id: 317, name: 'Dry Rosemary', price: 180.00, description: 'Dried rosemary leaves for seasoning. Price includes GST.', imageUrl: 'https://picsum.photos/seed/DryRosemary/400/400', category: 'Food & Beverage' },
  { id: 318, name: 'Dark Chocolate (Morde)', price: 400.00, description: 'Morde dark chocolate compound for baking. Price includes GST.', imageUrl: 'https://picsum.photos/seed/DarkChocolate/400/400', category: 'Food & Beverage' },
  { id: 319, name: 'Passion Fruit Pulp', price: 450.00, description: 'Exotic passion fruit pulp for drinks and desserts. Price includes GST.', imageUrl: 'https://picsum.photos/seed/PassionFruitPulp/400/400', category: 'Food & Beverage' },
  { id: 320, name: 'Litchi Crush', price: 290.00, description: 'Flavorful litchi crush for beverages. Price includes GST.', imageUrl: 'https://picsum.photos/seed/LitchiCrush/400/400', category: 'Food & Beverage' },
  { id: 321, name: 'Lime Seasoning Powder', price: 150.00, description: 'Zesty lime seasoning powder. Price includes GST.', imageUrl: 'https://picsum.photos/seed/LimeSeasoning/400/400', category: 'Food & Beverage' },
  { id: 322, name: 'Rye Flour', price: 180.00, description: 'Nutritious rye flour for baking. Price includes GST.', imageUrl: 'https://picsum.photos/seed/RyeFlour/400/400', category: 'Food & Beverage' },
  { id: 323, name: 'Red Cherry Filling', price: 520.00, description: 'Sweet red cherry filling for cakes and pastries. Price includes GST.', imageUrl: 'https://picsum.photos/seed/RedCherryFilling/400/400', category: 'Food & Beverage' },
  { id: 324, name: 'Gelatine', price: 300.00, description: 'Unflavored gelatine powder for culinary use. Price includes GST.', imageUrl: 'https://picsum.photos/seed/Gelatine/400/400', category: 'Food & Beverage' },
  { id: 325, name: 'Caramel Color', price: 220.00, description: 'Food-grade caramel color for baking and cooking. Price includes GST.', imageUrl: 'https://picsum.photos/seed/CaramelColor/400/400', category: 'Food & Beverage' },
  { id: 326, name: 'Choco Chip Dark', price: 380.00, description: 'Dark chocolate chips for cookies and desserts. Price includes GST.', imageUrl: 'https://picsum.photos/seed/ChocoChipDark/400/400', category: 'Food & Beverage' },
  { id: 327, name: 'Choco Chip White', price: 400.00, description: 'White chocolate chips for baking. Price includes GST.', imageUrl: 'https://picsum.photos/seed/ChocoChipWhite/400/400', category: 'Food & Beverage' },
  { id: 328, name: 'Mango Essence', price: 240.00, description: 'Concentrated mango essence for flavoring. Price includes GST.', imageUrl: 'https://picsum.photos/seed/MangoEssence/400/400', category: 'Food & Beverage' },
  { id: 329, name: 'Orange Essence', price: 230.00, description: 'Concentrated orange essence for flavoring. Price includes GST.', imageUrl: 'https://picsum.photos/seed/OrangeEssence/400/400', category: 'Food & Beverage' },
  { id: 330, name: 'Choclate Syrup (Hershey\'s) Btl.', price: 250.00, description: 'Classic Hershey\'s chocolate syrup bottle. Price includes GST.', imageUrl: 'https://picsum.photos/seed/ChocolateSyrup/400/400', category: 'Food & Beverage' },
  { id: 331, name: 'Coco Powder (Blossom)', price: 350.00, description: 'Blossom brand cocoa powder for baking. Price includes GST.', imageUrl: 'https://picsum.photos/seed/CocoaPowder/400/400', category: 'Food & Beverage' },
  { id: 332, name: 'Walnut Giri', price: 900.00, description: 'High-quality walnut kernels (giri). Price includes GST.', imageUrl: 'https://picsum.photos/seed/WalnutGiri/400/400', category: 'Food & Beverage' },
  { id: 333, name: 'Dry Oregano', price: 170.00, description: 'Dried oregano for seasoning Italian dishes. Price includes GST.', imageUrl: 'https://picsum.photos/seed/DryOregano/400/400', category: 'Food & Beverage' },
  { id: 334, name: 'Plain Natural Hot Glaze (Bakel)', price: 650.00, description: 'Bakel\'s plain natural hot glaze for a professional finish on pastries. Price includes GST.', imageUrl: 'https://picsum.photos/seed/HotGlaze/400/400', category: 'Food & Beverage' },
];

export const ALL_PRODUCTS: Product[] = [
  ...JANITORIAL_PRODUCTS,
  ...STATIONERY_PRODUCTS,
  ...PACKAGING_PRODUCTS,
  ...FOOD_AND_BEVERAGE_PRODUCTS,
];
